- README.md
- setup.py
- urbansim_templates/__init__.py
- urbansim_templates/modelmanager.py
- urbansim_templates/models/__init__.py
- urbansim_templates/models/binary_logit.py
- urbansim_templates/models/regression.py
- urbansim_templates/models/shared.py
This PR updates the OLS regression step template to match the functionality of binary logit:
- draws everything except constructor, `fit()`, and `run()` from the `TemplateStep()` parent class
- parameters can be added and edited at any time, `fit()` can be re-run at any time
- arguments are renamed to clearly distinguish estimation parameters from prediction parameters
Docstrings are in good shape; usage demonstration here: https://github.com/ual/urbansim_parcel_bayarea/blob/master/notebooks-sam/Demo.ipynb
This update will break previously saved OLS steps. I'm not intending to do this again, but to be safe we should save the notebooks used to generate model steps we like, in case they need to be re-run.
Overall status:
- OLS and binary logit templates are ready for use
- MNL (small choice …
> Updating OLS template

- setup.py
- urbansim_templates/modelmanager.py
- urbansim_templates/models/__init__.py
- urbansim_templates/models/binary_logit.py
- urbansim_templates/models/shared.py
- urbansim_templates/models/small_multinomial_logit.py
This PR adds a multinomial logit template for cases like travel mode choice, where the number of alternatives is small and we want to specify different utility functions for them. 
````
"Small" MNL:
- data is in a single table (choosers)
- each alternative can have a different model expression
- all the alternatives are available to all choosers
- estimation and simulation use the PyLogit engine (via ChoiceModels)
"Large" MNL:
- data is in two tables (choosers and alternatives)
- each alternative has the same model expression
- N alternatives are sampled for each chooser
- estimation and simulation use the ChoiceModels engine (formerly UrbanSim MNL)
````
This template ended up requiring a lot of custom code. Model estimation and predicted probabilities come from PyLogit via ChoiceModels, …
> Adding MNL template for small number of alternatives

- urbansim_templates/models/dcm.py
This PR fixes DCM to use a run() method without arguments, in line with recent changes in ModelManager that require this.
> Minor fixes to DCM

- setup.py
- urbansim_templates/modelmanager.py
- urbansim_templates/models/binary_logit.py
- urbansim_templates/models/large_multinomial_logit.py
- urbansim_templates/models/regression.py
- urbansim_templates/models/shared.py
- urbansim_templates/models/small_multinomial_logit.py
This PR adds version tracking to model steps' dictionary (and YAML) representations. 
Stored model step instances now include both the model manager codebase version (at the file level) and the template codebase version (at the model step level).
The rationale for this is that eventually we'll need/want to make changes that introduce incompatibilities with older versions of saved model steps. Tracking which version of the codebase created a saved model step will help us deal with updating and conversion.
This PR also moves the `register()` method out of the template parent class and into the individual templates, which resolves some bugs.
> Add version tracking

- setup.py
- urbansim_templates/models/large_multinomial_logit.py
- urbansim_templates/models/shared.py
- urbansim_templates/models/small_multinomial_logit.py
This PR updates the `LargeMultinomialLogitStep` template to provide probabilities and unconstrained choices when a fitted model is run.
Demonstration here: [Large-MNL-work.ipynb](https://github.com/ual/urbansim_parcel_bayarea/blob/0f15e5679e5ac89dd74fbc50790588ffca2538c2/notebooks-sam/Large-MNL-work.ipynb)
In most cases we will actually want _constrained_ choices, which are not yet implemented. See https://github.com/UDST/choicemodels/issues/26 for a discussion.
cc @waddell @Arezoo-bz @mxndrwgrdnr
> Updating large MNL to provide probabilities and unconstrained choices

- setup.py
- urbansim_templates/modelmanager.py
This PR implements consistent ordering when saved models are listed or written to a config file. (Model steps are sorted alphabetically by name.) This resolves Issue #13.
> Consistent model save order

- urbansim_templates/modelmanager.py
This is a quick fix that allows users to import `modelmanager` without having a config file in place. Users will be able to fit model steps but not save them. (More functionality is on the way.)
This is related to Issue #16.
- bumps package version to 0.1.dev7 in `setup.py`
- bumps MODELMANAGER_VERSION to 0.1.dev7
- individual template versions unchanged
> Quick fix for initialization bug when config file doesn't exist

- setup.py
- urbansim_templates/modelmanager.py
- urbansim_templates/models/small_multinomial_logit.py
This PR changes the initialization behavior of the library, enables custom locations for saved model steps, and switches to using separate files for each saved object. This is a disruptive set of changes, but should improve usability and pave the way for future features. This is discussed in Issue #16.
- API documentation is in the docstrings: [modelmanager.py](https://github.com/UDST/urbansim_templates/blob/f2e849efe0dab0afd40f88d23e8ba6e5af5fd16f/urbansim_templates/modelmanager.py)
- demonstration of new features: [Initialization.ipynb](https://github.com/ual/urbansim_parcel_bayarea/blob/9be8ea11a46d781ac1c98fd41e6aa4bd658ed4e1/notebooks-sam/Initialization.ipynb)
- new config format: [model-step-name.yaml](https://github.com/ual/urbansim_parcel_bayarea/blob/9be8ea11a46d781ac1c98fd41e6aa4 …
> Explicit initialization and multiple config files

- urbansim_templates/models/large_multinomial_logit.py
This is a small PR that adds code to save the estimation data table to the `LargeMultinomialLogitStep` class object for diagnostic use, after a model is estimated. For example, this lets users check which alternatives were sampled for each chooser.
The table is saved to the `mergedchoicetable` property, with type `choicemodels.tools.MergedChoiceTable`. To get the data, you can use:
````py
df = m.mergedchoicetable.to_frame()
````
- version numbers are unchanged
> Saving estimation data table to Large MNL class object

- .gitignore
- setup.py
- urbansim_templates/modelmanager.py
- urbansim_templates/models/large_multinomial_logit.py
- urbansim_templates/tests/README.md
- urbansim_templates/tests/configs/README.md
- urbansim_templates/tests/test_large_multinomial_logit.py
This PR adds an optional `chooser_sample_size` parameter for Large MNL. If provided, the model is estimated using a random sample of observations.
The objective is to enable faster model estimation in cases where the number of observations is very large. This also lays groundwork for cross-validation of fitted models. See issue #26.
- adds an optional `chooser_sample_size` parameter for Large MNL
- changes the ordering of Large MNL parameters to `chooser_filters`, `chooser_sample_size`, `alt_filters`, `alt_sample_size`
- adds tests for chooser sampling and persistence of the parameter when a model step is saved and reloaded
- increments the library version and modelmanager_version to 0.1.dev10
- increments the LargeMultinomialLogitStep template version to 0.1.dev3
> Adding chooser_sample_size parameter for Large MNL

- urbansim_templates/__init__.py
This PR adds the version number to the top-level `__init__.py` file. 
This is a python convention that allows users to invoke `urbansim_templates.__version__` to get info about which copy of the library has been loaded.
> Updating version location

- setup.py
- urbansim_templates/__init__.py
- urbansim_templates/modelmanager.py
- urbansim_templates/models/binary_logit.py
- urbansim_templates/models/large_multinomial_logit.py
- urbansim_templates/models/regression.py
- urbansim_templates/models/shared.py
- urbansim_templates/models/small_multinomial_logit.py
- urbansim_templates/tests/test_binary_logit.py
- urbansim_templates/tests/test_regression.py
- urbansim_templates/tests/test_small_multinomial_logit.py
This PR addresses issue #35.
It removes separate tracking of a `MODELMANAGER_VERSION` and a `TEMPLATE_VERSION`, substituting the current version number of the `urbansim_templates` library for both.
- the `type` parameter of a saved model step is renamed to `template` for clarity: this is generated automatically and is the template's class name
- the `version` parameter of a saved model step is renamed to `template_version` for clarity
This should not cause any backward compatibility issues.
- adds simple unit tests for each of the model steps, checking that models can be estimated, saved, and reloaded without errors
- updates the library version to `0.1.dev11`
> Simplify versioning

- README.md
- setup.py
- urbansim_templates/__init__.py
- urbansim_templates/modelmanager.py
- urbansim_templates/models/binary_logit.py
- urbansim_templates/models/large_multinomial_logit.py
- urbansim_templates/models/regression.py
- urbansim_templates/models/shared.py
- urbansim_templates/models/small_multinomial_logit.py
- urbansim_templates/tests/README.md
- urbansim_templates/tests/test_binary_logit.py
- urbansim_templates/tests/test_large_multinomial_logit.py
- urbansim_templates/tests/test_regression.py
- urbansim_templates/tests/test_small_multinomial_logit.py
This PR updates the ModelManager architecture, mainly to:
1. move the `register()` operation from the templates to `modelmanager`
2. remove potential circular imports
3. add support for supplemental objects like pickled model results
These changes were interrelated, so i ended up implementing them together.
The `register()` method was the only place where templates accessed `modelmanager` directly, so removing it allows us to avoid potential circular references. This resolves issue #40.
```py
m = <configured template object>
m.register()  # old usage, disabled by this PR
modelmanager.register(m)  # new usage
```
(This operation passes a configured template object to ModelManager, which registers it with the task orchestrator and saves it to disk for future reuse.)
"Supplemental objects" …
> ModelManager architecture updates

- README.md
- setup.py
- urbansim_templates/__init__.py
- urbansim_templates/modelmanager.py
- urbansim_templates/models/binary_logit.py
- urbansim_templates/models/large_multinomial_logit.py
- urbansim_templates/models/regression.py
- urbansim_templates/models/small_multinomial_logit.py
This PR implements a `@modelmanager.template` decorator. This is the approach we decided on in issue #42 for registering templates with ModelManager.
Add the decorator to a template class definition:
```py
import modelmanager
@modelmanager.template
class MyTemplate()
...
```
This makes the class available to the currently running instance of ModelManager whenever it's imported. ModelManager needs access to the classes in order to load saved steps from disk.
This uses the same approach as Orca registrations, which is nice. And it's a good solution for allowing users to make custom templates.
All the prior unit tests are passing.
- updates the library version to 0.1.dev13
> Adding template decorators

- setup.py
- urbansim_templates/__init__.py
- urbansim_templates/models/large_multinomial_logit.py
- urbansim_templates/models/small_multinomial_logit.py
- urbansim_templates/tests/test_large_multinomial_logit.py
This PR updates the `LargeMultinomialLogitStep` template with better simulation functionality. 
It requires ChoiceModels 0.2.dev4, aka [choicemodels PR #44](https://github.com/UDST/choicemodels/pull/44).
- Adds some new template parameters for choice simulation:
- `constrained_choices`: True/False
- `alt_capacity`: column from the `out_alternatives` table
- `chooser_size`: column from the `out_choosers` table
- `max_iter`: maximum number of choice simulation iterations to allow, only relevant in unusual situations where it's difficult to match choosers to appropriate alternatives
- Updates the `run()` method to use new simulation utilities from ChoiceModels: `monte_carlo_choices()` for unconstrained simulation and `iterative_lottery_choices()` for constrained simulation. 
- Improves unit …
> Updating Large MNL template with better simulation functionality

- setup.py
- urbansim_templates/__init__.py
- urbansim_templates/models/large_multinomial_logit.py
- urbansim_templates/models/segmented_large_multinomial_logit.py
- urbansim_templates/tests/test_segmented_large_multinomial_logit.py
this PR addresses:
- #58 
- latest changes to choicemodels library (specifically [this](https://github.com/UDST/choicemodels/pull/48) PR)
- adds a couple new tests to reflect the changes
> latest updates to segmented MNL

- setup.py
- urbansim_templates/__init__.py
- urbansim_templates/models/small_multinomial_logit.py
- urbansim_templates/tests/test_small_multinomial_logit.py
This PR fixes a bug: when a Small MNL model was saved, the `model_expression` was inadvertently being deleted from the copy of the model step in memory. This is now fixed, with a unit test added that confirms it. Should resolve issue #71.
> [0.1.dev20] Bugfix: Small MNL model_expression persistence

- CHANGELOG.md
- setup.py
- tests/test_regression.py
- urbansim_templates/__init__.py
- urbansim_templates/models/regression.py
This PR fixes a bug where OLS simulation raised an error when the output column didn't exist yet. This functionality should have been included in PR #79, but I missed it.
- implements optional `out_transform` for OLS simulation
- this is dev release 0.1.dev25
> [0.1.dev25] Fixing bug with OLS simulation to new output column

- .gitignore
- CHANGELOG.md
- setup.py
- urbansim_templates/__init__.py
This PR converts the v0.1.dev25 developer release into the v0.1 production release. 
Looks like there's one more bug to fix, but this version is already up on PyPI, so there will be an 0.1.1 following shortly.
> [0.1] First production release!

- urbansim_templates/models/large_multinomial_logit.py
This must have slipped off my radar in the fall, but this is a PR that ties out with [PR 45](https://github.com/UDST/choicemodels/pull/45) in choicemodels, adding support for passing in multiple tables of interaction terms into a large MNL simulation.
> Multi interactions

- urbansim_templates/models/small_multinomial_logit.py
forgot to include this in the last PR. Small MNL uses `out_tables` instead out `out_choosers` like large MNL. updated accordingly.
> change out_choosers to out_tables syntax to match small MNL

- CHANGELOG.md
- MANIFEST.in
- README.md
- docs/source/index.rst
- setup.py
- urbansim_templates/__init__.py
New release. 
- bug fixes
- includes license file in the source distribution
- 0.1.1
> [0.1.1] Production release

- CHANGELOG.md
- docs/source/index.rst
- setup.py
- tests/test_small_multinomial_logit.py
- urbansim_templates/__init__.py
- urbansim_templates/models/shared.py
- urbansim_templates/models/small_multinomial_logit.py
This PR fixes a problem in the Small MNL template that was causing crashes in the simulation stage. This was identified by @xyzjayne. 
Small MNL model steps were crashing in the simulation stage if the output column didn't exist yet, or in certain cases when multiple tables were being assembled.
When data was being assembled for simulation, the older `TemplateStep._get_data()` method was requesting the `out_column` because we used to update it locally before updating Orca ([shared.py#L194](https://github.com/UDST/urbansim_templates/blob/5b8a3b37914e632370aee8c72c7d1e3afcd5f31f/urbansim_templates/models/shared.py#L194)). This caused errors when the column didn't exist yet.
It was also requesting the `choice_column` even when simulating, because of a coding mistake involving the special …
> [0.2.dev1] Fixes Small MNL simulation crash

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
This PR improves the documentation:
- updates `CONTRIBUTING.md` to include additional clarity and detail borrowed from ChoiceModels
- adds a section on patching earlier releases
- changes the format of `CHANGELOG.md` to group dev releases within the associated production release
unchanged
> Updates contribution guide

- .travis.yml
- CHANGELOG.md
- docs/source/conf.py
- docs/source/data-templates.rst
- docs/source/index.rst
- docs/source/utilities.rst
- setup.py
- tests/test_column_expression.py
- tests/test_shared_core.py
- tests/test_shared_output_column.py
- urbansim_templates/__init__.py
- urbansim_templates/data/__init__.py
- urbansim_templates/data/column_from_expression.py
- urbansim_templates/data/load_table.py
- urbansim_templates/data/save_table.py
- urbansim_templates/modelmanager.py
- urbansim_templates/shared/__init__.py
- urbansim_templates/shared/core.py
- urbansim_templates/shared/output_column.py
- urbansim_templates/utils.py
This PR adds the first "settings objects," as proposed in issue #54 and sketched out for the column templates in issue https://github.com/UDST/urbansim_templates/issues/98#issuecomment-478752890. This lets common sets of parameters be defined in a single place, improving consistency and reducing the amount of repeated code.
- `shared.CoreTemplateSettings`, with parameters for all templates
- `shared.OutputColumnSettings`, for any template that generates or modifies a column
- `data.ExpressionSettings`, with custom parameters for the `ColumnFromExpression` template
- `shared.register_column()`, to register a callable as an Orca column
- `utils.col_in_expression()`, to extract column names from a `df.eval()`-style expression
This allows us to restructure the inputs of the first column …
> [0.2.dev6] Introducing settings objects

- CHANGELOG.md
- docs/source/index.rst
- setup.py
- tests/test_regression.py
- urbansim_templates/__init__.py
- urbansim_templates/models/regression.py
This PR fixes the behavior of the `out_transform` parameter in `OLSRegressionStep`. 
Transformations weren't working, generating errors either when a model step was fit or saved or run, depending on the data format provided. This was identified by @cvanoli -- thanks!
I fixed the code and updated/clarified the documentation.
The bug was from a combination of two things -- a parameter formatting discrepancy between the core UrbanSim class (`urbansim.models.RegressionModel`) and the templates, which was exacerbated when we changed how the out-transformations work in 0.1.dev25 (#82). 
Our documentation used to say that the `out_transform` parameter should be provided as a callable, but it should actually be a string with the function name. Any element-wise function from numpy or python's …
> [0.2.dev7] Bug fix for "out_transform" parameter in OLSRegressionStep

- CHANGELOG.md
- docs/source/index.rst
- setup.py
- tests/test_regression.py
- urbansim_templates/__init__.py
- urbansim_templates/models/regression.py
This PR applies the patch from PR #111 (0.2.dev7) to the 0.1.x codebase, so we can release it on pip and conda immediately. The patch fixes the behavior of the `out_transform` parameter in OLS simulation.
0.1.3
> [0.1.3] Patch for "out_transform" in OLS simulation
